version: '3.7'
services: 
    database:
        image: mysql
        container_name: database
        environment: 
            MYSQL_DATABASE: projPI
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: tuchinski
            MYSQL_PASSWORD: 123
        ports: 
            - "3306:3306"
        networks: 
            - banco-backend
    backend:
        image: tuchinski/projintegrador:v1.1
        container_name: spring_boot_atual
        environment: 
            SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/projPI?useSSL=false&allowPublicKeyRetrieval=true
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root  
        ports: 
            - "8080:8080"           
        depends_on: 
            - database
        networks: 
            - banco-backend           
networks:
    banco-backend:
        driver: bridge